-- Address Table
CREATE TABLE ADDRESS
(
    NUMBER INTEGER,
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    STREET CHARACTER VARYING(255)
);

-- Bank Table
CREATE TABLE BANK
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME CHARACTER VARYING(255)
);

-- Customer Table
CREATE TABLE CUSTOMER
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME CHARACTER VARYING(255)
);

-- Customer_Address Join Table (for Many-to-Many relationship)
CREATE TABLE CUSTOMER_ADDRESS
(
    ADDRESS_ID BIGINT NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    PRIMARY KEY (ADDRESS_ID, CUSTOMER_ID),
    CONSTRAINT FK_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ID),
    CONSTRAINT FK_CUSTOMER_ADDRESS FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

-- Family Table
CREATE TABLE FAMILY
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPTION CHARACTER VARYING(255)
);

-- Job Table
CREATE TABLE JOB
(
    SALARY DOUBLE PRECISION NOT NULL,
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    JOBDESCR CHARACTER VARYING(255)
);

-- Pincode Table
CREATE TABLE PINCODE
(
    COUNT INTEGER,
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PINCODE CHARACTER VARYING(255)
);

-- Credit Card Table
CREATE TABLE CREDITCARD
(
    BALANCE INTEGER,
    CREDITLIMIT INTEGER,
    NUMBER INTEGER,
    BANK_ID BIGINT,
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PINCODE_ID BIGINT,
    CONSTRAINT FK_BANK FOREIGN KEY (BANK_ID) REFERENCES BANK(ID),
    CONSTRAINT FK_PINCODE FOREIGN KEY (PINCODE_ID) REFERENCES PINCODE(ID)
);

-- Customer_CreditCard Join Table (for Many-to-Many relationship)
CREATE TABLE CUSTOMER_CREDITCARD
(
    CREDITCARD_ID BIGINT NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    PRIMARY KEY (CREDITCARD_ID, CUSTOMER_ID),
    CONSTRAINT FK_CREDITCARD FOREIGN KEY (CREDITCARD_ID) REFERENCES CREDITCARD(ID),
    CONSTRAINT FK_CUSTOMER_CREDITCARD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

