
    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        bank_id bigint,
        id bigint generated by default as identity,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_address (
        address_id bigint not null,
        customer_id bigint not null
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null
    );

    create table Family (
        id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table Job (
        salary float(53) not null,
        id bigint generated by default as identity,
        jobDescr varchar(255),
        primary key (id)
    );

    create table Person (
        family_id bigint,
        id bigint generated by default as identity,
        firstName varchar(255),
        lastName varchar(255),
        primary key (id)
    );

    create table Person_Job (
        Person_id bigint not null,
        jobList_id bigint not null unique
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        pincode varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists CreditCard 
       add constraint FKe2wqhnxpkjp87b3eyfq6gl39a 
       foreign key (bank_id) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_address 
       add constraint FK4n1t9cnxhkev5vdbedu0ao068 
       foreign key (address_id) 
       references Address;

    alter table if exists customer_address 
       add constraint FK7dy564lg4tac3m50d3ws4mhc4 
       foreign key (customer_id) 
       references Customer;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;

    alter table if exists Person 
       add constraint FKq5c84kpy1ioamtt7ht5c270dm 
       foreign key (family_id) 
       references Family;

    alter table if exists Person_Job 
       add constraint FKb784yqmsn896esmtk1xnlbj5m 
       foreign key (jobList_id) 
       references Job;

    alter table if exists Person_Job 
       add constraint FKjgqlaq1rryygfeeo6v0uhjy7p 
       foreign key (Person_id) 
       references Person;

    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        bank_id bigint,
        id bigint generated by default as identity,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_address (
        address_id bigint not null,
        customer_id bigint not null
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null
    );

    create table Family (
        id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table Job (
        salary float(53) not null,
        id bigint generated by default as identity,
        jobDescr varchar(255),
        primary key (id)
    );

    create table Person (
        family_id bigint,
        id bigint generated by default as identity,
        firstName varchar(255),
        lastName varchar(255),
        primary key (id)
    );

    create table Person_Job (
        Person_id bigint not null,
        jobList_id bigint not null unique
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        pincode varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists CreditCard 
       add constraint FKe2wqhnxpkjp87b3eyfq6gl39a 
       foreign key (bank_id) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_address 
       add constraint FK4n1t9cnxhkev5vdbedu0ao068 
       foreign key (address_id) 
       references Address;

    alter table if exists customer_address 
       add constraint FK7dy564lg4tac3m50d3ws4mhc4 
       foreign key (customer_id) 
       references Customer;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;

    alter table if exists Person 
       add constraint FKq5c84kpy1ioamtt7ht5c270dm 
       foreign key (family_id) 
       references Family;

    alter table if exists Person_Job 
       add constraint FKb784yqmsn896esmtk1xnlbj5m 
       foreign key (jobList_id) 
       references Job;

    alter table if exists Person_Job 
       add constraint FKjgqlaq1rryygfeeo6v0uhjy7p 
       foreign key (Person_id) 
       references Person;

    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        bank_id bigint,
        id bigint generated by default as identity,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_address (
        address_id bigint not null,
        customer_id bigint not null
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null
    );

    create table Family (
        id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table Job (
        salary float(53) not null,
        id bigint generated by default as identity,
        jobDescr varchar(255),
        primary key (id)
    );

    create table Person (
        family_id bigint,
        id bigint generated by default as identity,
        firstName varchar(255),
        lastName varchar(255),
        primary key (id)
    );

    create table Person_Job (
        Person_id bigint not null,
        jobList_id bigint not null unique
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        pincode varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists CreditCard 
       add constraint FKe2wqhnxpkjp87b3eyfq6gl39a 
       foreign key (bank_id) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_address 
       add constraint FK4n1t9cnxhkev5vdbedu0ao068 
       foreign key (address_id) 
       references Address;

    alter table if exists customer_address 
       add constraint FK7dy564lg4tac3m50d3ws4mhc4 
       foreign key (customer_id) 
       references Customer;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;

    alter table if exists Person 
       add constraint FKq5c84kpy1ioamtt7ht5c270dm 
       foreign key (family_id) 
       references Family;

    alter table if exists Person_Job 
       add constraint FKb784yqmsn896esmtk1xnlbj5m 
       foreign key (jobList_id) 
       references Job;

    alter table if exists Person_Job 
       add constraint FKjgqlaq1rryygfeeo6v0uhjy7p 
       foreign key (Person_id) 
       references Person;

    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        bank_id bigint,
        id bigint generated by default as identity,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_address (
        address_id bigint not null,
        customer_id bigint not null
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null
    );

    create table Family (
        id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table Job (
        salary float(53) not null,
        id bigint generated by default as identity,
        jobDescr varchar(255),
        primary key (id)
    );

    create table Person (
        family_id bigint,
        id bigint generated by default as identity,
        firstName varchar(255),
        lastName varchar(255),
        primary key (id)
    );

    create table Person_Job (
        Person_id bigint not null,
        jobList_id bigint not null unique
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        pincode varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists CreditCard 
       add constraint FKe2wqhnxpkjp87b3eyfq6gl39a 
       foreign key (bank_id) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_address 
       add constraint FK4n1t9cnxhkev5vdbedu0ao068 
       foreign key (address_id) 
       references Address;

    alter table if exists customer_address 
       add constraint FK7dy564lg4tac3m50d3ws4mhc4 
       foreign key (customer_id) 
       references Customer;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;

    alter table if exists Person 
       add constraint FKq5c84kpy1ioamtt7ht5c270dm 
       foreign key (family_id) 
       references Family;

    alter table if exists Person_Job 
       add constraint FKb784yqmsn896esmtk1xnlbj5m 
       foreign key (jobList_id) 
       references Job;

    alter table if exists Person_Job 
       add constraint FKjgqlaq1rryygfeeo6v0uhjy7p 
       foreign key (Person_id) 
       references Person;

    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        bank_id bigint,
        id bigint generated by default as identity,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_address (
        address_id bigint not null,
        customer_id bigint not null
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null
    );

    create table Family (
        id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table Job (
        salary float(53) not null,
        id bigint generated by default as identity,
        jobDescr varchar(255),
        primary key (id)
    );

    create table Person (
        family_id bigint,
        id bigint generated by default as identity,
        firstName varchar(255),
        lastName varchar(255),
        primary key (id)
    );

    create table Person_Job (
        Person_id bigint not null,
        jobList_id bigint not null unique
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        pincode varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists CreditCard 
       add constraint FKe2wqhnxpkjp87b3eyfq6gl39a 
       foreign key (bank_id) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_address 
       add constraint FK4n1t9cnxhkev5vdbedu0ao068 
       foreign key (address_id) 
       references Address;

    alter table if exists customer_address 
       add constraint FK7dy564lg4tac3m50d3ws4mhc4 
       foreign key (customer_id) 
       references Customer;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;

    alter table if exists Person 
       add constraint FKq5c84kpy1ioamtt7ht5c270dm 
       foreign key (family_id) 
       references Family;

    alter table if exists Person_Job 
       add constraint FKb784yqmsn896esmtk1xnlbj5m 
       foreign key (jobList_id) 
       references Job;

    alter table if exists Person_Job 
       add constraint FKjgqlaq1rryygfeeo6v0uhjy7p 
       foreign key (Person_id) 
       references Person;

    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        bank_id bigint,
        id bigint generated by default as identity,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_address (
        address_id bigint not null,
        customer_id bigint not null
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null
    );

    create table Family (
        id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table Job (
        salary float(53) not null,
        id bigint generated by default as identity,
        jobDescr varchar(255),
        primary key (id)
    );

    create table Person (
        family_id bigint,
        id bigint generated by default as identity,
        firstName varchar(255),
        lastName varchar(255),
        primary key (id)
    );

    create table Person_Job (
        Person_id bigint not null,
        jobList_id bigint not null unique
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        pincode varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists CreditCard 
       add constraint FKe2wqhnxpkjp87b3eyfq6gl39a 
       foreign key (bank_id) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_address 
       add constraint FK4n1t9cnxhkev5vdbedu0ao068 
       foreign key (address_id) 
       references Address;

    alter table if exists customer_address 
       add constraint FK7dy564lg4tac3m50d3ws4mhc4 
       foreign key (customer_id) 
       references Customer;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;

    alter table if exists Person 
       add constraint FKq5c84kpy1ioamtt7ht5c270dm 
       foreign key (family_id) 
       references Family;

    alter table if exists Person_Job 
       add constraint FKb784yqmsn896esmtk1xnlbj5m 
       foreign key (jobList_id) 
       references Job;

    alter table if exists Person_Job 
       add constraint FKjgqlaq1rryygfeeo6v0uhjy7p 
       foreign key (Person_id) 
       references Person;

    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        bank_id bigint,
        id bigint generated by default as identity,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_address (
        address_id bigint not null,
        customer_id bigint not null
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null
    );

    create table Family (
        id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table Job (
        salary float(53) not null,
        id bigint generated by default as identity,
        jobDescr varchar(255),
        primary key (id)
    );

    create table Person (
        family_id bigint,
        id bigint generated by default as identity,
        firstName varchar(255),
        lastName varchar(255),
        primary key (id)
    );

    create table Person_Job (
        Person_id bigint not null,
        jobList_id bigint not null unique
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        pincode varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists CreditCard 
       add constraint FKe2wqhnxpkjp87b3eyfq6gl39a 
       foreign key (bank_id) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_address 
       add constraint FK4n1t9cnxhkev5vdbedu0ao068 
       foreign key (address_id) 
       references Address;

    alter table if exists customer_address 
       add constraint FK7dy564lg4tac3m50d3ws4mhc4 
       foreign key (customer_id) 
       references Customer;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;

    alter table if exists Person 
       add constraint FKq5c84kpy1ioamtt7ht5c270dm 
       foreign key (family_id) 
       references Family;

    alter table if exists Person_Job 
       add constraint FKb784yqmsn896esmtk1xnlbj5m 
       foreign key (jobList_id) 
       references Job;

    alter table if exists Person_Job 
       add constraint FKjgqlaq1rryygfeeo6v0uhjy7p 
       foreign key (Person_id) 
       references Person;

    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        bank_id bigint,
        id bigint generated by default as identity,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_address (
        address_id bigint not null,
        customer_id bigint not null
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null
    );

    create table Family (
        id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table Job (
        salary float(53) not null,
        id bigint generated by default as identity,
        jobDescr varchar(255),
        primary key (id)
    );

    create table Person (
        family_id bigint,
        id bigint generated by default as identity,
        firstName varchar(255),
        lastName varchar(255),
        primary key (id)
    );

    create table Person_Job (
        Person_id bigint not null,
        jobList_id bigint not null unique
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        pincode varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists CreditCard 
       add constraint FKe2wqhnxpkjp87b3eyfq6gl39a 
       foreign key (bank_id) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_address 
       add constraint FK4n1t9cnxhkev5vdbedu0ao068 
       foreign key (address_id) 
       references Address;

    alter table if exists customer_address 
       add constraint FK7dy564lg4tac3m50d3ws4mhc4 
       foreign key (customer_id) 
       references Customer;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;

    alter table if exists Person 
       add constraint FKq5c84kpy1ioamtt7ht5c270dm 
       foreign key (family_id) 
       references Family;

    alter table if exists Person_Job 
       add constraint FKb784yqmsn896esmtk1xnlbj5m 
       foreign key (jobList_id) 
       references Job;

    alter table if exists Person_Job 
       add constraint FKjgqlaq1rryygfeeo6v0uhjy7p 
       foreign key (Person_id) 
       references Person;

    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        bank_id bigint,
        id bigint generated by default as identity,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_address (
        address_id bigint not null,
        customer_id bigint not null
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null
    );

    create table Family (
        id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table Job (
        salary float(53) not null,
        id bigint generated by default as identity,
        jobDescr varchar(255),
        primary key (id)
    );

    create table Person (
        family_id bigint,
        id bigint generated by default as identity,
        firstName varchar(255),
        lastName varchar(255),
        primary key (id)
    );

    create table Person_Job (
        Person_id bigint not null,
        jobList_id bigint not null unique
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        pincode varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists CreditCard 
       add constraint FKe2wqhnxpkjp87b3eyfq6gl39a 
       foreign key (bank_id) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_address 
       add constraint FK4n1t9cnxhkev5vdbedu0ao068 
       foreign key (address_id) 
       references Address;

    alter table if exists customer_address 
       add constraint FK7dy564lg4tac3m50d3ws4mhc4 
       foreign key (customer_id) 
       references Customer;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;

    alter table if exists Person 
       add constraint FKq5c84kpy1ioamtt7ht5c270dm 
       foreign key (family_id) 
       references Family;

    alter table if exists Person_Job 
       add constraint FKb784yqmsn896esmtk1xnlbj5m 
       foreign key (jobList_id) 
       references Job;

    alter table if exists Person_Job 
       add constraint FKjgqlaq1rryygfeeo6v0uhjy7p 
       foreign key (Person_id) 
       references Person;

    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        bank_id bigint,
        id bigint generated by default as identity,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_address (
        address_id bigint not null,
        customer_id bigint not null
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null
    );

    create table Family (
        id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table Job (
        salary float(53) not null,
        id bigint generated by default as identity,
        jobDescr varchar(255),
        primary key (id)
    );

    create table Person (
        family_id bigint,
        id bigint generated by default as identity,
        firstName varchar(255),
        lastName varchar(255),
        primary key (id)
    );

    create table Person_Job (
        Person_id bigint not null,
        jobList_id bigint not null unique
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        pincode varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists CreditCard 
       add constraint FKe2wqhnxpkjp87b3eyfq6gl39a 
       foreign key (bank_id) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_address 
       add constraint FK4n1t9cnxhkev5vdbedu0ao068 
       foreign key (address_id) 
       references Address;

    alter table if exists customer_address 
       add constraint FK7dy564lg4tac3m50d3ws4mhc4 
       foreign key (customer_id) 
       references Customer;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;

    alter table if exists Person 
       add constraint FKq5c84kpy1ioamtt7ht5c270dm 
       foreign key (family_id) 
       references Family;

    alter table if exists Person_Job 
       add constraint FKb784yqmsn896esmtk1xnlbj5m 
       foreign key (jobList_id) 
       references Job;

    alter table if exists Person_Job 
       add constraint FKjgqlaq1rryygfeeo6v0uhjy7p 
       foreign key (Person_id) 
       references Person;

    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        bank_id bigint,
        id bigint generated by default as identity,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_address (
        address_id bigint not null,
        customer_id bigint not null
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null
    );

    create table Family (
        id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table Job (
        salary float(53) not null,
        id bigint generated by default as identity,
        jobDescr varchar(255),
        primary key (id)
    );

    create table Person (
        family_id bigint,
        id bigint generated by default as identity,
        firstName varchar(255),
        lastName varchar(255),
        primary key (id)
    );

    create table Person_Job (
        Person_id bigint not null,
        jobList_id bigint not null unique
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        pincode varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists CreditCard 
       add constraint FKe2wqhnxpkjp87b3eyfq6gl39a 
       foreign key (bank_id) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_address 
       add constraint FK4n1t9cnxhkev5vdbedu0ao068 
       foreign key (address_id) 
       references Address;

    alter table if exists customer_address 
       add constraint FK7dy564lg4tac3m50d3ws4mhc4 
       foreign key (customer_id) 
       references Customer;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;

    alter table if exists Person 
       add constraint FKq5c84kpy1ioamtt7ht5c270dm 
       foreign key (family_id) 
       references Family;

    alter table if exists Person_Job 
       add constraint FKb784yqmsn896esmtk1xnlbj5m 
       foreign key (jobList_id) 
       references Job;

    alter table if exists Person_Job 
       add constraint FKjgqlaq1rryygfeeo6v0uhjy7p 
       foreign key (Person_id) 
       references Person;

    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        bank_id bigint,
        id bigint generated by default as identity,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_address (
        address_id bigint not null,
        customer_id bigint not null
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null
    );

    create table Family (
        id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table Job (
        salary float(53) not null,
        id bigint generated by default as identity,
        jobDescr varchar(255),
        primary key (id)
    );

    create table Person (
        family_id bigint,
        id bigint generated by default as identity,
        firstName varchar(255),
        lastName varchar(255),
        primary key (id)
    );

    create table Person_Job (
        Person_id bigint not null,
        jobList_id bigint not null unique
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        pincode varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists CreditCard 
       add constraint FKe2wqhnxpkjp87b3eyfq6gl39a 
       foreign key (bank_id) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_address 
       add constraint FK4n1t9cnxhkev5vdbedu0ao068 
       foreign key (address_id) 
       references Address;

    alter table if exists customer_address 
       add constraint FK7dy564lg4tac3m50d3ws4mhc4 
       foreign key (customer_id) 
       references Customer;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;

    alter table if exists Person 
       add constraint FKq5c84kpy1ioamtt7ht5c270dm 
       foreign key (family_id) 
       references Family;

    alter table if exists Person_Job 
       add constraint FKb784yqmsn896esmtk1xnlbj5m 
       foreign key (jobList_id) 
       references Job;

    alter table if exists Person_Job 
       add constraint FKjgqlaq1rryygfeeo6v0uhjy7p 
       foreign key (Person_id) 
       references Person;
